steps:
  # Terraform Init
  - name: 'hashicorp/terraform:latest'
    args: ['init']

  # Terraform Plan
  - name: 'hashicorp/terraform:latest'
    args: ['plan']

  # Terraform Apply
  - name: 'hashicorp/terraform:latest'
    args: ['apply', '-auto-approve']

  # Setup gcloud and kubectl context
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'private-cluster1', '--region', 'asia-south2', '--project', 'project-7989']

  # Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    id: Deploy_to_kubernetes
    env:
      - 'CLOUDSDK_COMPUTE_REGION=asia-south2'
      - 'CLOUDSDK_CONTAINER_CLUSTER=private-cluster1'
      - 'KUBECTL_VERSION=1.29'

  # Wait for 20 minutes
  - name: 'ubuntu'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - 'sleep 1200' # 20 minutes in seconds

  # Terraform Destroy
  - name: 'hashicorp/terraform:latest'
    args: ['destroy', '-auto-approve']

options:
  pool:
    name: projects/project-7989/locations/asia-south2/workerPools/my-private-pool    


options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
