steps:
  # Terraform Init
  - name: 'hashicorp/terraform:latest'
    args: ['init']

  # Terraform Plan
  - name: 'hashicorp/terraform:latest'
    args: ['plan']

  # Terraform Apply
  - name: 'hashicorp/terraform:latest'
    args: ['apply', '-auto-approve']

  # Setup gcloud and kubectl context
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['container', 'clusters', 'get-credentials', 'private-cluster1', '--zone', 'asia-south2', '--project', 'project-7989']

  # Deploy to Kubernetes
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'k8s/']
    id: Deploy to Kubernetes

timeout: '1200s'

options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
