name: Provision, Deploy, and Scheduled Destroy

on:
  workflow_dispatch:

jobs:
  build:
    name: Deploy Infrastructure and Application
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
        
    
    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    - name: install the gcloud cli
      uses: google-github-actions/setup-gcloud@v2.1.0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        install_components: 'gke-gcloud-auth-plugin'
        export_default_credentials: true
     
    - name: Get service account key from secrets
      uses: google-github-actions/get-secret@v1
      id: get-sa-key
      with:
        secret_name: GCP_SA_KEY

    - name: Authenticate with service account and get K8s credentials
      run: |
        gcloud auth activate-service-account --key-file "$GCP_SA_KEY"
        gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.GCP_REGION }} --project "${{ secrets.GCP_PROJECT_ID }}"

    
    - name: Deploy Application
      run: |
        kubectl apply -f k8s/nginx-namespace.yaml
        kubectl apply -f k8s/nginx-deployment.yaml
        kubectl apply -f k8s/nginx-service.yaml
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
        GCP_REGION: ${{ secrets.GCP_REGION }}

  destroy:
    name: Scheduled Destroy Infrastructure
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Wait for 25 minutes
        uses: jakejarvis/wait-action@main
        with:
          time: '25m'

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK (Again for Destroy)
        uses: google-github-actions/setup-gcloud@v2.1.0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install Terraform (Again for Destroy)
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init (For Destroy)
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
